USE UniversityDW;
GO

ALTER TABLE Performance NOCHECK CONSTRAINT ALL;
ALTER TABLE Lecturer NOCHECK CONSTRAINT ALL;
ALTER TABLE Department NOCHECK CONSTRAINT ALL;
ALTER TABLE Student NOCHECK CONSTRAINT ALL;
ALTER TABLE Major NOCHECK CONSTRAINT ALL;
ALTER TABLE Subject NOCHECK CONSTRAINT ALL;
ALTER TABLE Time NOCHECK CONSTRAINT ALL;
ALTER TABLE Junk NOCHECK CONSTRAINT ALL;
ALTER TABLE Faculty NOCHECK CONSTRAINT ALL;
GO

-- 2. Clear tables
TRUNCATE TABLE Performance;  -- Fact table first (truncate is OK)

DELETE FROM Lecturer;
DELETE FROM Department;
DELETE FROM Student;
DELETE FROM Major;
DELETE FROM Subject;
DELETE FROM Time;
DELETE FROM Junk;
DELETE FROM Faculty;
GO

-- 3. Re-enable constraints
ALTER TABLE Performance WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Lecturer WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Department WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Student WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Major WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Subject WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Time WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Junk WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE Faculty WITH CHECK CHECK CONSTRAINT ALL;
GO

-- 4. Reset identity seeds (optional, to start IDs from 1 again)
DBCC CHECKIDENT ('Faculty', RESEED, 0);
DBCC CHECKIDENT ('Department', RESEED, 0);
DBCC CHECKIDENT ('Major', RESEED, 0);
DBCC CHECKIDENT ('Subject', RESEED, 0);
DBCC CHECKIDENT ('Time', RESEED, 0);
DBCC CHECKIDENT ('Student', RESEED, 0);
DBCC CHECKIDENT ('Lecturer', RESEED, 0);
DBCC CHECKIDENT ('Junk', RESEED, 0);
-- Performance has no IDENTITY, no reseed needed
GO

PRINT 'UniversityDW cleared successfully.';
